controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
initial:  # Define initial robot poses per group
  - group: arm
    pose: rest